name: Gallilearn BFF Web

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  call-workflow:
    uses: JoaooArtur/gallilearn-pipelines/.github/workflows/workflow_fargate.yaml@main
    with:
      path: ./src/Web
      project: WebBff
      test: src/Tests/WebBff.Tests
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      AZURE_CREDENTIAlS: ${{ secrets.AZURE_CREDENTIAlS }} 
      